package presentacion;

import entidades.*;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.regex.PatternSyntaxException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author deerfox@debian
 */

public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        
        titleLbl.setIcon(contactsIcon);
        searchIconLbl.setIcon(searchIcon);
        addBtn.setIcon(addIcon);
        editBtn.setIcon(editIcon);
        removeBtn.setIcon(removeIcon);
        themeBtn.setIcon(darkmodeIcon);
        
        list = new ListaContactos();
        
        ctbl = new ControlTabla(list);
        
        contactsTable.setModel(ctbl.getModelo());
        
        ctbl.getModelo().addColumn("Apellido");
        ctbl.getModelo().addColumn("Nombre");
        ctbl.getModelo().addColumn("Teléfono Fijo");
        ctbl.getModelo().addColumn("Celular");
        ctbl.getModelo().addColumn("E-mail");
        
        contactsTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        contactsTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if (!lse.getValueIsAdjusting() && contactsTable.getSelectedRow() != -1) {
                    editBtn.setEnabled(true);
                    removeBtn.setEnabled(true);
                }
            }
        });
        
        ctbl.updateModelo(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        contactsScrollPanel = new javax.swing.JScrollPane();
        contactsTable = new javax.swing.JTable();
        searchTxt = new javax.swing.JTextField();
        searchIconLbl = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        themeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda Electrónica");
        setResizable(false);

        titleLbl.setFont(new java.awt.Font("Fira Sans", 1, 24)); // NOI18N
        titleLbl.setText("Contactos");

        contactsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        contactsScrollPanel.setViewportView(contactsTable);

        searchTxt.setToolTipText("Buscar por Apellido...");
        searchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtActionPerformed(evt);
            }
        });
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTxtKeyTyped(evt);
            }
        });

        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setEnabled(false);
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        removeBtn.setEnabled(false);
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        themeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(themeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchIconLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(contactsScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchIconLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(contactsScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addComponent(removeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                    .addComponent(themeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static boolean confirmar(String pregunta){
        boolean confirmado = false;
        int resultado = JOptionPane.showConfirmDialog(null, pregunta, "Confirmación", JOptionPane.YES_NO_OPTION);
        if (resultado == JOptionPane.YES_OPTION){
            confirmado = true;
        } else if (resultado == JOptionPane.NO_OPTION){
            confirmado = false;
        }
        return confirmado;
    }    
    
    private void searchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtActionPerformed

    private void themeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeBtnActionPerformed
        try {
            if (!darkModeEnabled){
                javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf());
                SwingUtilities.updateComponentTreeUI(this);
                this.pack();
                darkModeEnabled = true;
                themeBtn.setIcon(lightmodeIcon);
            } else {
                javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
                SwingUtilities.updateComponentTreeUI(this);
                this.pack();
                darkModeEnabled = false;
                themeBtn.setIcon(darkmodeIcon);                
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_themeBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        new FrmAgregarContacto(ctbl, list).setVisible(true);
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        int selection = contactsTable.getSelectedRow();
        if (selection != -1) {
            int modelIndex = contactsTable.convertRowIndexToModel(selection);
            new FrmEditarContacto(ctbl, list, list.getLista().get(modelIndex)).setVisible(true);
        } else {
            editBtn.setEnabled(false); removeBtn.setEnabled(false);
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        int selection = contactsTable.getSelectedRow();
        if (selection != -1) {
            int modelIndex = contactsTable.convertRowIndexToModel(selection);
            Contacto c = list.getLista().get(modelIndex);
            if (confirmar("¿Desea eliminar al contacto " +
                c.getNombre() + " " + c.getApellido() + "?")) {
                list.getLista().remove(modelIndex);
                list.guardar();
                ctbl.updateModelo(list);
            }
        } else {
            editBtn.setEnabled(false); removeBtn.setEnabled(false);
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void searchTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyTyped
        /*
            Solución implementada gracias a la valiosa ayuda
            de mi compañero Jonathan Mostacero
        */
        trs = new TableRowSorter(ctbl.getModelo());
        searchTxt.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                try {
                    trs.setRowFilter(RowFilter.regexFilter(searchTxt.getText(), 0));
                } catch (PatternSyntaxException err) {
                    JOptionPane.showMessageDialog(null,
                    "Término de búsqueda inválido.\nInténtelo nuevamente.",
                    "Búsqueda inválida", 2);
                    searchTxt.setText(null);
                }
            }
        });
        contactsTable.setRowSorter(trs);
    }//GEN-LAST:event_searchTxtKeyTyped

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf Light look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.out.println(ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JScrollPane contactsScrollPanel;
    private javax.swing.JTable contactsTable;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JLabel searchIconLbl;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JButton themeBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables

    //ImageIcons
    private final ImageIcon contactsIcon = new ImageIcon("icons/48/contacts.png");
    private final ImageIcon searchIcon = new ImageIcon("icons/36/search_glass.png");
    private final ImageIcon addIcon = new ImageIcon("icons/36/add.png");
    private final ImageIcon editIcon = new ImageIcon("icons/36/edit.png");
    private final ImageIcon removeIcon = new ImageIcon("icons/36/remove.png"); 
    private final ImageIcon darkmodeIcon = new ImageIcon("icons/36/darkmode.png");
    private final ImageIcon lightmodeIcon = new ImageIcon("icons/36/lightmode.png");
    
    private ListaContactos list;
    private ControlTabla ctbl;
    private TableRowSorter trs;

    public ControlTabla getCtbl() {
        return ctbl;
    }

    public void setCtbl(ControlTabla ctbl) {
        this.ctbl = ctbl;
    }
    
    private boolean darkModeEnabled = false;
    
    public boolean isDarkModeEnabled(){
        return darkModeEnabled;
    }
    
    public ListaContactos getList() {
        return list;
    }

    public void setList(ListaContactos list) {
        this.list = list;
    }
}
