package ui;

import entidades.*;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author deerfox@debian
 */

public class FrmAgregarContacto extends javax.swing.JFrame {

    /**
     * Creates new form FrmAgregarContacto
     */
    public FrmAgregarContacto(){}
    
    public FrmAgregarContacto(ControlTabla ctbl, ListaContactos list) {
        try {
            this.fTitle = Font.createFont(Font.TRUETYPE_FONT, this.getClass().getResourceAsStream("/fonts/MerriweatherSans-Bold.ttf")).deriveFont(22f);
            this.fElement1 = Font.createFont(Font.TRUETYPE_FONT, this.getClass().getResourceAsStream("/fonts/MerriweatherSans-Regular.ttf")).deriveFont(14f);
            this.fElementM = Font.createFont(Font.TRUETYPE_FONT, this.getClass().getResourceAsStream("/fonts/MerriweatherSans-Medium.ttf")).deriveFont(15f);
            this.fElementB = Font.createFont(Font.TRUETYPE_FONT, this.getClass().getResourceAsStream("/fonts/MerriweatherSans-Bold.ttf")).deriveFont(16f);
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(SwingContacts.class.getName()).log(Level.SEVERE, null, ex);
        }

        initComponents();

        javax.swing.UIManager.put("OptionPane.messageFont", new FontUIResource(fElement1));
        
        this.ctbl = ctbl;
        this.list = list;
        
        javax.swing.UIManager.put("Label.font", fTitle);
        
        ImageIcon addContactIcon = new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"));
        ImageIcon lastnameIcon = new javax.swing.ImageIcon(getClass().getResource("/iconos/lastname.png"));
        ImageIcon nameIcon = new javax.swing.ImageIcon(getClass().getResource("/iconos/name.png"));
        ImageIcon phoneIcon = new javax.swing.ImageIcon(getClass().getResource("/iconos/phone.png"));
        ImageIcon cellphoneIcon = new javax.swing.ImageIcon(getClass().getResource("/iconos/cellphone.png"));
        ImageIcon emailIcon = new javax.swing.ImageIcon(getClass().getResource("/iconos/email.png"));
        ImageIcon saveIcon = new javax.swing.ImageIcon(getClass().getResource("/iconos/check.png"));
        ImageIcon discardIcon = new javax.swing.ImageIcon(getClass().getResource("/iconos/close.png"));
        
        titleLbl.setIcon(addContactIcon);
        lastnameLbl.setIcon(lastnameIcon);
        nameLbl.setIcon(nameIcon);
        phoneLbl.setIcon(phoneIcon);
        cellphoneLbl.setIcon(cellphoneIcon);
        emailLbl.setIcon(emailIcon);
        saveBtn.setIcon(saveIcon);
        discardBtn.setIcon(discardIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        lastnameTxt = new javax.swing.JTextField();
        lastnameLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        phoneLbl = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        cellphoneLbl = new javax.swing.JLabel();
        cellphoneTxt = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        discardBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir Contacto");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(this.fElement1);
        setResizable(false);

        titleLbl.setFont(fTitle);
        titleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add_48.png"))); // NOI18N
        titleLbl.setText("Agregar Contacto");

        lastnameTxt.setFont(fElement1);

        lastnameLbl.setFont(fElementM);
        lastnameLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lastname.png"))); // NOI18N
        lastnameLbl.setLabelFor(lastnameTxt);
        lastnameLbl.setText("Apellido:");

        nameLbl.setFont(fElementM);
        nameLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/name.png"))); // NOI18N
        nameLbl.setLabelFor(nameTxt);
        nameLbl.setText("Nombre:");

        nameTxt.setFont(fElement1);

        phoneLbl.setFont(fElementM);
        phoneLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/phone.png"))); // NOI18N
        phoneLbl.setLabelFor(phoneTxt);
        phoneLbl.setText("Teléfono Fijo:");

        phoneTxt.setFont(fElement1);
        phoneTxt.setName(""); // NOI18N

        cellphoneLbl.setFont(fElementM);
        cellphoneLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cellphone.png"))); // NOI18N
        cellphoneLbl.setLabelFor(cellphoneTxt);
        cellphoneLbl.setText("Celular:");

        cellphoneTxt.setFont(fElement1);

        emailLbl.setFont(fElementM);
        emailLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/email.png"))); // NOI18N
        emailLbl.setLabelFor(emailTxt);
        emailLbl.setText("Correo electrónico:");

        emailTxt.setFont(fElement1);

        saveBtn.setFont(fElementB);
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/check.png"))); // NOI18N
        saveBtn.setText("Guardar");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        discardBtn.setFont(fElementB);
        discardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/close.png"))); // NOI18N
        discardBtn.setText("Descartar");
        discardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailLbl)
                    .addComponent(cellphoneLbl)
                    .addComponent(phoneLbl)
                    .addComponent(nameLbl)
                    .addComponent(lastnameLbl)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(discardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nameTxt)
                    .addComponent(phoneTxt)
                    .addComponent(cellphoneTxt)
                    .addComponent(emailTxt)
                    .addComponent(lastnameTxt)
                    .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lastnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phoneLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cellphoneLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cellphoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void discardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_discardBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        Contacto c = new Contacto(lastnameTxt.getText(), nameTxt.getText(),
                     phoneTxt.getText(), cellphoneTxt.getText(), emailTxt.getText());
        list.registrar(c);
        ctbl.updateModelo(list);
        if (list.guardar()) {
            this.dispose();            
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private ControlTabla ctbl;
    private ListaContactos list;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cellphoneLbl;
    private javax.swing.JTextField cellphoneTxt;
    private javax.swing.JButton discardBtn;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel lastnameLbl;
    private javax.swing.JTextField lastnameTxt;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
    
    // Fonts
    private Font fTitle;
    private Font fElement1;
    private Font fElementM;
    private Font fElementB;
}
